FROM golang:1.5

RUN go get github.com/influxdb/influxdb && \
    cd $GOPATH/src/github.com/influxdb && \
    go get -u -f -t ./...

RUN cd $GOPATH/src/github.com/influxdb && \
    CGO_ENABLED=0 go install -a -installsuffix cgo -ldflags "-s" ./...

RUN mkdir /data
ADD influxdb.conf /etc/influxdb.conf
EXPOSE 8088 8083 8086 25826 4242
CMD influxd -config /etc/influxdb.conf

